advice_and_planning_categories = [
'Divorce & Family Law',
'Criminal Defense Law',
'Real Estate Law',
'Medical Law',
'Personal Injury Law',
'Workers Compensation Law',
'Bankruptcy Law',
'Estate Planning Law',
'Business Law',
'Disability Law',
'Tenant and Eviction Law',
'Traffic Ticketing Law',
'Immigration Law',
'Tax Law',
'Employment Law',
'Contract Law',
'Social Security Law',
'Patent Law',
'IP & Internet Law',
'Entertainment Law',
'Wills',
'Trusts',
'& Probates',
'Mediators',
'Tax Services',
'Accountants',
'Insurance',
'Financial Services',
'Check Cashing/Pay-day Loans',
'Title Loans',
'Banks & Credit Unions',
'Life Insurance',
'Auto Insurance',
'Home & Rental Insurance',
'Auto Loan Providers',
'Installment Loans',
'Mortgage Lenders',
'Pet Insurance',
]