food_categories = ['Breweries',
'Pizza',
'Restaurants',
'Chicken Wings',
'Burgers',
'Caterers',
'Street Vendors',
'Barbeque',
'Food Trucks',
'Breakfast & Brunch',
'French',
'Sandwiches',
'Cafes',
'Coffee & Tea',
'Bakeries',
'Thai',
'Mexican',
'Japanese',
'Cajun/Creole',
'Southern',
'Pakistani',
'Indian',
'Middle Eastern',
'Delis',
'Tapas/Small Plates',
'Poutineries',
'Supper Clubs',
'Fast Food',
'Canadian (New)',
'Beer',
'Wine & Spirits',
'Italian',
'American (Traditional)',
'Ice Cream & Frozen Yogurt',
'Seafood',
'Donuts',
'Soup',
'Salad',
'Latin American',
'Asian Fusion',
'Chinese',
'Vegetarian',
'Caribbean',
'Desserts',
'Steakhouses',
'Belgian',
'German',
'American (New)',
'Tea Rooms',
'Taiwanese',
'Fish & Chips',
'Ethnic Food',
'Specialty Food',
'Imported Food',
'Hot Dogs',
'Vietnamese',
'Comfort Food',
'Hungarian',
'Local Flavor',
'Chocolatiers & Shops',
'Coffee Roasteries',
'Coffee & Tea Supplies',
'Persian/Iranian',
'Brewpubs',
'Sushi Bars',
'Herbs & Spices',
'Candy Stores',
'Bubble Tea',
'Juice Bars & Smoothies',
'Fruits & Veggies',
'Diners',
'Food Stands',
'Brazilian',
'Gluten-Free',
'Vegan',
'Dim Sum',
'Bagels',
'Hookah Bars',
'Vitamins & Supplements',
'Organic Stores',
'Mediterranean',
'Patisserie/Cake Shop',
'Argentine',
'Greek',
'Irish',
'Chicken Shop',
'Meat Shops',
'Seafood Markets',
'Tacos',
'Cheesesteaks',
'Szechuan',
'Venezuelan',
'Soul Food',
'Noodles',
'Turkish',
'Afghan',
'Muay Thai',
'British',
'Cupcakes',
'Delicatessen',
'African',
'Fondue',
'Arabian',
'Ramen',
'Peruvian',
'Falafel',
'New Mexican Cuisine',
'Cantonese',
'Cuban',
'Dominican',
'Custom Cakes',
'Cafeteria',
'Waffles',
'Popcorn Shops',
'Sri Lankan',
'Mongolian',
'Modern European',
'Armenian',
'Hakka',
'Wine Tasting Room',
'Bangladeshi',
'Hong Kong Style Cafe',
'Himalayan/Nepalese',
'Moroccan',
'Lebanese',
'Eastern European',
'Polish',
'Scandinavian',
'Kebab',
'Ethiopian',
'Izakaya',
'Bavarian',
'Eatertainment',
'Coffeeshops',
'Tai Chi',
'Acai Bowls',
'Colombian',
'Food Banks',
'South African',
'Slovakian',
'Pan Asian',
'Syrian',
'Malaysian',
'Egyptian',
'Puerto Rican',
'Tuscan',
'Pop-Up Restaurants',
'Australian',
'Laotian',
'Scottish',
'Trinidadian',
'Honduran',
'Burmese',
'Haitian',
'Bulgarian',
'Shanghainese',
'Pub Food',
'Uzbek',
'Senegalese',
'Mauritius',
'Swiss Food',
'Sicilian',
'Nicaraguan',
'Japanese Curry',
'Czech/Slovakian',
'Northern German',
'Rotisserie Chicken',
'Pita',
'Udon',
'Chilean',
'Tex-Mex',
'Gastropubs',
'Gay Bars',
'Korean',
'Poke',
'Bistros',
'Shaved Ice',
'Buffets',
'Filipino',
'Portuguese',
'Spanish',
'Pasta Shops',
'Beer Gardens',
'Hawaiian',
'Basque',
'Gelato',
'Pretzels',
'Kosher',
'Russian',
'Food Court',
'Hot Pot',
'Smokehouse',
'Donairs',
'Singaporean',
'Salvadoran',
'Themed Cafes',
'Wraps',
'Ukrainian',
'Empanadas',
'Milkshake Bars',
'Macarons',
'Indonesian',
'Shaved Snow',
'Cambodian',
'Sugar Shacks',
'Teppanyaki',
'Austrian',
'Baguettes',
'Hainan',
'Conveyor Belt Sushi',
'Signature Cuisine',
'Iberian',
'Kombucha',
'Czech',
'Traditional Norwegian',
'Tonkatsu',
'Tempura',
'Churros',
'Soba',
'Serbo Croatian',
'Japanese Sweets']