grooming_categories = [
'Beauty & Spas',
'Barbers',
'Hair Salons',
'Skin Care',
'Hair Extensions',
'Medical Spas',
'Waxing',
'Nail Salons',
'Eyelash Service',
'Hair Removal',
'Blow Dry/Out Services',
'Hair Stylists',
'Day Spas',
'Massage',
'Massage Therapy',
'Eyebrow Services',
'Tattoo Removal',
'Kids Hair Salons',
'Saunas',
'Hot Tub & Pool',
'Laser Hair Removal',
'Men\'s Hair Salons',
'Threading Services',
'Henna Artists',
'Tattoo',
'Head Shops',
'Nail Technicians',
'Teeth Whitening',
'Erotic Massage',
'Aestheticians',
'Float Spa',
'Face Painting',
'Tui Na',
]