health_and_doctor_categories = [
'Optometrists',
'Eyewear & Opticians',
'Health & Medical',
'Cryotherapy',
'Physical Therapy',
'Diagnostic Imaging',
'Diagnostic Services',
'Dentists',
'Cosmetic Dentists',
'General Dentistry',
'Drugstores',
'Medical Supplies',
'Urologists',
'Doctors',
'Weight Loss Centers',
'Periodontists',
'Orthodontists',
'Orthopedists',
'Endodontists',
'Pediatric Dentists',
'Obstetricians & Gynecologists',
'Laser Eye Surgery/Lasik',
'Ophthalmologists',
'Oral Surgeons',
'Reflexology',
'Medical Centers',
'Dermatologists',
'Psychologists',
'Counseling & Mental Health',
'Naturopathic/Holistic',
'Acupuncture',
'Neurologist',
'Spine Surgeons',
'Cosmetic Surgeons',
'Retina Specialists',
'Emergency Rooms',
'Urgent Care',
'Hospitals',
'Chiropractors',
'Sports Medicine',
'Nutritionists',
'Prosthodontists',
'Kids Activities',
'Orthotics',
'Prosthetics',
'Pediatricians',
'Traditional Chinese Medicine',
'Podiatrists',
'Pain Management',
'Radiologists',
'Anesthesiologists',
'Sleep Specialists',
'Hydrotherapy',
'Psychiatrists',
'Estheticians',
'Rheumatologists',
'Surgeons',
'Speech Therapists',
'Preventive Medicine',
'Osteopathic Physicians',
'Oncologist',
'Cardiologists',
'Pulmonologist',
'Endocrinologists',
'Neurotologists',
'Hepatologists',
'Dietitians',
'Proctologists',
'Immunodermatologists',
'Vascular Medicine',
'Sports Psychologists',
'Undersea/Hyperbaric Medicine',
'Medical Foot Care',
'Ayurveda',
'Nephrologists',
'Pathologists',
'Phlebologists',
'Dialysis Clinics',
'Neuropathologists',
'Otologists',
'Reiki',
'Internal Medicine',
'Colonics',
'Prenatal/Perinatal Care',
'Alternative Medicine',
'Cannabis Clinics',
'Gastroenterologist',
'Allergists',
'Fertility',
'Plastic Surgeons',
'Ear Nose & Throat',
'Halotherapy',
'Acne Treatment',
'Addiction Medicine',
'Dental Hygienists',
'Hair Loss Centers',
'Occupational Therapy',
'Walk-in Clinics',
'Sex Therapists',
'Emergency Medicine',
'Gerontologists',
'Osteopaths',
'Toxicologists',
]