learning_categories = [
'Performing Arts',
'Art Schools',
'Martial Arts',
'Art Classes',
'Dance Studios',
'Cycling Classes',
'Dance Schools',
'Cosmetology Schools',
'Language Schools',
'Vocational & Technical School',
'Barre Classes',
'Swimming Lessons/Schools',
'First Aid Classes',
'Massage Schools',
'Challenge Courses',
'Test Preparation',
'Parenting Classes',
'Photography Classes',
'Adult Education',
'Tutoring Centers',
'Montessori Schools',
'Flight Instruction',
'Cooking Schools',
'Cooking Classes',
'Pole Dancing Classes',
'Private Schools',
'Wine Tasting Classes',
'Tasting Classes',
'Bartending Schools',
'Calligraphy',
'Ski Schools',
'Nursing Schools',
'Cheese Tasting Classes',
'Traffic Schools',
'Spin Classes',
'Waldorf Schools',
'DUI Schools',
'Middle Schools & High Schools',
'Elementary Schools',
'Colleges & Universities',
'Religious Schools',
'Preschools',
]