municipal_categories = [
'Community Service/Non-Profit',
'Amateur Sports Teams',
'Police Departments',
'Professional Sports Teams',
'Synagogues',
'Buses',
'Mass Media',
'Television Stations',
'Courthouses',
'Print Media',
'Radio Stations',
'Hindu Temples',
'Train Stations',
'Mosques',
'Health Insurance Offices',
'Embassy',
'Donation Center',
'Halfway Houses',
'Municipality',
'Civic Center',
'Veterans Organizations',
'Metro Stations',
'Jails & Prisons',
'Registry Office',
'Trains',
'Town Hall',
'Recycling Center',
'Departments of Motor Vehicles',
'Public Services & Government'
]