services_categories = [
'Event Planning & Services',
'Local Services',
'Automotive',
'Electronics Repair',
'Home Services',
'Masonry/Concrete',
'Professional Services',
'Contractors',
'Home Automation',
'Security Systems',
'Gardeners',
'Landscape Architects',
'Retirement Homes',
'Auto Customization',
'Auto Security',
'Car Stereo Installation',
'Interior Design',
'Flooring',
'Cabinetry',
'Refinishing Services',
'Tiling',
'Plumbing',
'Auto Repair',
'Motorcycle Rental',
'Scooter Rentals',
'Scooter Tours',
'Bike Rentals',
'Car Rental',
'Truck Rental',
'ATV Rentals/Tours',
'Movers',
'Gas Stations',
'Car Wash',
'Shipping Centers',
'Printing Services',
'Signmaking',
'Snow Removal',
'Gutter Services',
'Photographers',
'Food Delivery Services',
'Makeup Artists',
'Appliances & Repair',
'IT Services & Computer Repair',
'Mobile Phone Repair',
'Watch Repair',
'Oil Change Stations',
'Door Sales/Installation',
'Glass & Mirrors',
'Auto Detailing',
'Keys & Locksmiths',
'Apartments',
'Real Estate',
'Fabric Stores',
'Arts & Crafts',
'Spray Tanning',
'Tanning Beds',
'Tanning',
'Party & Event Planning',
'DUI Law',
'Lawyers',
'Divorce & Family Law',
'Criminal Defense Law',
'Transmission Repair',
'Furniture Reupholstery',
'Auto Upholstery',
'Notaries',
'Mailbox Centers',
'Limos',
'Specialty Schools',
'Education',
'Home Staging',
'Estate Liquidation',
'Home Organization',
'Carpet Cleaning',
'Office Cleaning',
'Home Cleaning',
'Pest Control',
'Wildlife Control',
'Body Shops',
'Dog Walkers',
'Home Inspectors',
'Property Management',
'Wedding Planning',
'DJs',
'Internet Service Providers',
'Officiants',
'Home Decor',
'Screen Printing/T-Shirt Printing',
'Sewing & Alterations',
'Embroidery & Crochet',
'Packing Services',
'Handyman',
'Land Surveying',
'Real Estate Law',
'Real Estate Services',
'Electricians',
'Damage Restoration',
'Roofing',
'Dry Cleaning & Laundry',
'Laundry Services',
'Heating & Air Conditioning/HVAC',
'Water Purification Services',
'Smog Check Stations',
'Supernatural Readings',
'Career Counseling',
'Recycling Center',
'Junk Removal & Hauling',
'Party Bus Rentals',
'Private Tutors',
'Walking Tours',
'Customized Merchandise',
'Pet Adoption',
'Party Equipment Rentals',
'Windshield Installation & Repair',
'Auto Glass Services',
'Bespoke Clothing',
'Business Consulting',
'Dry Cleaning',
'Carpeting',
'Carpet Installation',
'Furniture Assembly',
'Furniture Repair',
'Pool & Hot Tub Service',
'Pool Cleaners',
'Architects',
'Home Theatre Installation',
'Security Services',
'Event Photography',
'Session Photography',
'Mortgage Brokers',
'Bridal',
'Nanny Services',
'Floral Designers',
'Mortuary Services',
'Funeral Services & Cemeteries',
'Framing',
'Firearm Training',
'Home Energy Auditors',
'Insulation Installation',
'Couriers & Delivery Services',
'Laundromat',
'Advertising',
'Television Service Providers',
'Wheel & Rim Repair',
'Golf Lessons',
'Marketing',
'Web Design',
'Art Classes',
'Patio Coverings',
'Artificial Turf',
'Creperies',
'Appraisal Services',
'Jewelry Repair',
'Dance Studios',
'Piercing',
'Motorcycle Repair',
'Drywall Installation & Repair',
'Painters',
'Permanent Makeup',
'Water Heater Installation/Repair',
'Air Duct Cleaning',
'Vacation Rental Agents',
'Parking',
'Commercial Real Estate',
'Registration Services',
'Carpenters',
'Dance Schools',
'Opera & Ballet',
'Tree Services',
'Irrigation',
'Medical Law',
'Personal Injury Law',
'Workers Compensation Law',
'General Litigation',
'Trampoline Parks',
'Summer Camps',
'Septic Services',
'Home Health Care',
'Internet Cafes',
'Metal Fabricators',
'Musical Instruments & Teachers',
'Misting System Services',
'Self-defense Classes',
'Brazilian Jiu-jitsu',
'Sugaring',
'Video/Film Production',
'Hospice',
'Memory Care',
'Assisted Living Facilities',
'Window Washing',
'Home Window Tinting',
'Car Window Tinting',
'Countertop Installation',
'Bankruptcy Law',
'Estate Planning Law',
'Post Offices',
'Videos & Video Game Rental',
'Employment Agencies',
'Business Law',
'Disability Law',
'Musical Instrument Services',
'Aquarium Services',
'Karate',
'Driving Schools',
'Pet Photography',
'Paintball',
'Glass Blowing',
'Special Education',
'Bartenders',
'Passport & Visa Services',
'Solar Installation',
'CPR Classes',
'Bike Repair/Maintenance',
'Data Recovery',
'Roadside Assistance',
'Music Production Services',
'Photo Booth Rentals',
'Team Building Activities',
'Shredding Services',
'Payroll Services',
'Legal Services',
'Business Financing',
'Motorsport Vehicle Repairs',
'Translation Services',
'Meditation Centers',
'TV Mounting',
'Windows Installation',
'Vacation Rentals',
'Machine & Tool Rental',
'Tenant and Eviction Law',
'Pet Transportation',
'Paint & Sip',
'Fire Protection Services',
'Aircraft Repairs',
'IV Hydration',
'Vehicle Wraps',
'Mobile Dent Repair',
'Gunsmith',
'Videographers',
'Game Truck Rental',
'Holiday Decorations',
'Boat Charters',
'Engraving',
'Trailer Repair',
'RV Repair',
'Boat Repair',
'Commissioned Artists',
'Cremation Services',
'Fireplace Services',
'Pet Waste Removal',
'Car Inspectors',
'Personal Assistants',
'Travel Agents',
'RV Rental',
'Wallpapering',
'Adoption Services',
'Car Brokers',
'Car Buyers',
'Farm Equipment Repair',
'Editorial Services',
'Bookkeepers',
'Powder Coating',
'Sandblasting',
'Commercial Truck Repair',
'Chimney Sweeps',
'Childproofing',
'Laboratory Testing',
'Public Relations',
'Town Car Service',
'Generator Installation/Repair',
'Private Investigation',
'Debt Relief Services',
'Bail Bondsmen',
'Grout Services',
'Skilled Nursing',
'Party Bike Rentals',
'Personal Care Services',
'Health Coach',
'Solar Panel Cleaning',
'Pet Cremation Services',
'Body Contouring',
'Excavation Services',
'Lawn Services',
'Immigration Law',
'Talent Agencies',
'Golf Cart Rentals',
'Stucco Services',
'Trailer Rental',
'Currency Exchange',
'Ultrasound Imaging Centers',
'Clock Repair',
'College Counseling',
'Foundation Repair',
'Waterproofing',
'Tax Law',
'Employment Law',
'Recording & Rehearsal Studios',
'Magicians',
'Holiday Decorating Services',
'Clothing Rental',
'Holistic Animal Care',
'Carpet Dyeing',
'Vehicle Shipping',
'Dumpster Rental',
'Real Estate Photography',
'Public Markets',
'Demolition Services',
'Placenta Encapsulations',
'Day Camps',
'Car Auctions',
'Pet Breeders',
'Homeless Shelters',
'3D Printing',
'Audio/Visual Equipment Rental',
'Feng Shui',
'Furniture Rental',
'Striptease Dancers',
'Auto Electric Services',
'Medical Cannabis Referrals',
'Concept Shops',
'Nurse Practitioner',
'Software Development',
'Knife Sharpening',
'Mobility Equipment Sales & Services',
'Private Jet Charter',
'Car Share Services',
'Beach Equipment Rentals',
'Clowns',
'Pensions',
'Valet Services',
'Luggage Storage',
'Elder Care Planning',
'Apartment Agents',
'Animal Physical Therapy',
'Behavior Analysts',
'Cheerleading',
'Structural Engineers',
'Hazardous Waste Disposal',
'Art Space Rentals',
'Patent Law',
'Fire Departments',
'IP & Internet Law',
'Public Adjusters',
'Hybrid Car Repair',
'Customs Brokers',
'Bike Repair',
'Duplication Services',
'Crane Services',
'Mobile Home Repair',
'Indoor Landscaping',
'Well Drilling',
'Bike Parking',
'Home Developers',
'Petting Zoos',
'Sport Equipment Hire',
'Billing Services',
'Infectious Disease Specialists',
'Aviation Services',
'Animal Assisted Therapy',
'Street Art',
'Self Storage',
'Family Practice',
'Travel Services',
'Life Coach',
'Financial Advising',
'Child Care & Day Care',
'Investing',
'Graphic Design',
'Garage Door Services',
'Emergency Pet Hospital',
'Lactation Services',
'Boudoir Photography',
'Childbirth Education',
'Roof Inspectors',
'Medical Transportation',
'Homeowner Association',
'Musicians',
'Piano Services',
'Home Network Installation',
'House Sitters',
'Bounce House Rentals',
'Vocal Coach',
'Art Restoration',
'Amusement Parks',
'Screen Printing',
'Pet Training',
'Real Estate Agents',
'Doulas',
'Visitor Centers',
'Boot Camps',
'Shoe Repair',
'Educational Services',
'Luggage',
'Towing',
'Photography Stores & Services',
'Shutters',
'Awnings',
'Environmental Testing',
'Psychics',
'Shared Office Spaces',
'Environmental Abatement',
'Rehabilitation Center',
'Do-It-Yourself Food',
'Airport Shuttles',
'Water Delivery',
'Ice Delivery',
'Personal Chefs',
'Hydro-jetting',
'Caricatures',
'Siding',
'Animal Shelters',
'University Housing',
'Balloon Services',
'Bingo Halls',
'Midwives',
'Backflow Services',
'Condominiums',
'Audiologist',
'Shoe Shine',
'EV Charging Stations',
'Blood & Plasma Donation Centers',
'Bike Sharing',
'Fingerprinting',
'Astrologers',
'Psychic Mediums',
'Concierge Medicine',
'Party Characters',
'Lice Services',
'Bookbinding',
'Taxidermy',
'Matchmakers',
'Service Stations',
'Process Servers',
'Mobile Home Parks',
'Digitizing Services',
'Product Design',
'DIY Auto Shop',
'Senior Centers',
'Tickets',
'Trivia Hosts',
'Habilitative Services',
'Bus Rental',
'Fuel Docks',
'Backshop',
'Makerspaces',
'Court Reporters',
'Market Stalls',
'Sauna Installation & Repair',
'Pets',
'Pet Groomers',
'Pet Services',
'Pet Boarding',
'Veterinarians',
'Pet Stores',
'Pet Sitting',
]