shopping_categories = [
'Home & Garden',
'Nurseries & Gardening',
'Flowers & Gifts',
'Gift Shops',
'Fashion',
'Department Stores',
'Landscaping',
'Electronics',
'Kitchen & Bath',
'Grocery',
'Thrift Stores',
'Used',
'Vintage & Consignment',
'Antiques',
'Auction Houses',
'Motorcycle Dealers',
'Pawn Shops',
'Jewelry',
'Mattresses',
'Furniture Stores',
'Tobacco Shops',
'Vape Shops',
'Auto Parts & Supplies',
'Watches',
'Discount Store',
'Wholesale Stores',
'Outlet Stores',
'Florists',
'Personal Shopping',
'Tires',
'Women\'s Clothing',
'Cosmetics & Beauty Supply',
'Car Dealers',
'Packing Supplies',
'Mobile Phone Accessories',
'Mobile Phones',
'Telecommunications',
'Appliances',
'Building Supplies',
'Health Markets',
'Baby Gear & Furniture',
'Convenience Stores',
'Vinyl Records',
'Books',
'Mags',
'Accessories',
'Children\'s Clothing',
'Hardware Stores',
'Men\'s Clothing',
'Party Supplies',
'Lingerie',
'Formal Wear',
'Sports Wear',
'Sporting Goods',
'Shoe Stores',
'Mini Golf',
'Outdoor Gear',
'Propane',
'Bookstores',
'Toy Stores',
'Cards & Stationery',
'Guns & Ammo',
'Libraries',
'Swimwear',
'Wigs',
'Computers',
'Bikes',
'Golf Equipment',
'Video Game Stores',
'Used Car Dealers',
'Farmers Market',
'Newspapers & Magazines',
'Ethical Grocery',
'Public Transportation',
'Shades & Blinds',
'Comic Books',
'Hobby Shops',
'Golf Cart Dealers',
'Lighting Stores',
'Pressure Washers',
'Battery Stores',
'Art Supplies',
'Fences & Gates',
'Souvenir Shops',
'Aquariums',
'Local Fish Stores',
'Leather Goods',
'Butcher',
'Motorcycle Gear',
'Halal',
'Guitar Stores',
'Golf Equipment Shops',
'Gold Buyers',
'Maternity Wear',
'International Grocery',
'Fitness/Exercise Equipment',
'Hunting & Fishing Supplies',
'Paint Stores',
'Cannabis Dispensaries',
'Farming Equipment',
'Kitchen Incubators',
'Hats',
'Brasseries',
'RV Parks',
'Water Stores',
'Tableware',
'Kitchen Supplies',
'Utilities',
'Pop-up Shops',
'Decks & Railing',
'Outdoor Furniture Stores',
'Knitting Supplies',
'Mobile Home Dealers',
'Livestock Feed & Supply',
'Machine Shops',
'Safe Stores',
'Cheese Shops',
'RV Dealers',
'Trailer Dealers',
'Brewing Supplies',
'Costumes',
'Trophy Shops',
'Wholesalers',
'Boat Dealers',
'Surf Shop',
'Christmas Trees',
'Duty-Free Shops',
'Used Bookstore',
'Ethnic Grocery',
'Dinner Theater',
'Motorsport Vehicle Dealers',
'Hockey Equipment',
'Teacher Supplies',
'Hearing Aid Providers',
'Piano Stores',
'Grilling Equipment',
'Dance Wear',
'Herbal Shops',
'Safety Equipment',
'Interlock Systems',
'Restaurant Supplies',
'Sunglasses',
'Fur Clothing',
'Olive Oil',
'Boat Parts & Supplies',
'Commercial Truck Dealers',
'Bike Shop',
'Bicycles',
'Props',
'Junkyards',
'Water Suppliers',
'Hearing Aids',
'Playsets',
'Electricity Suppliers',
'Natural Gas Suppliers',
'Music & Video',
'Music & DVDs',
'Shopping Centers',
'Spiritual Shop',
'Plus Size Fashion',
'Candle Stores',
'Lighting Fixtures & Equipment',
'Tabletop Games',
'Rugs',
'Office Equipment',
'Pharmacy',
'CSA',
'Aircraft Dealers',
'Military Surplus',
'Live/Raw Food',
'Honey',
'Skate Shops',
'Flea Markets',
'Ski & Snowboard Shops',
'Horse Equipment Shops',
'Uniforms',
'Firewood',
'Ticket Sales',
'Beverage Store',
'Flowers',
'Perfume',
'Storefront Clinics',
'Hydroponics',
'Religious Items',
'High Fidelity Audio Equipment',
'Pedicabs',
'Gemstones & Minerals',
'Fireworks',
'Christmas Markets',
'Game Meat',
'Traditional Clothing',
'Ceremonial Clothing',
'Drones',
'Fishmonger',
]