sports_categories = [
'Active Life',
'Trainers',
'Gyms',
'Sports Clubs',
'Fitness & Instruction',
'Bowling',
'Boxing',
'Yoga',
'Gymnastics',
'Circuit Training Gyms',
'Cardio Classes',
'Pilates',
'Kickboxing',
'Taekwondo',
'Soccer',
'Badminton',
'Chinese Martial Arts',
'Batting Cages',
'Free Diving',
'Races & Competitions',
'Aerial Fitness',
'Qi Gong',
'Airsoft',
'Surfing',
'Tubing',
'Bubble Soccer',
'Fencing Clubs',
'Interval Training Gyms',
]