travel_and_leisure_categories = [
'Museums',
'Stadiums & Arenas',
'Resorts',
'Lounges',
'Dance Clubs',
'Playgrounds',
'Skate Parks',
'Swimming Pools',
'Skating Rinks',
'Beaches',
'Comedy Clubs',
'Jazz & Blues',
'Cinema',
'Airport Lounges',
'Recreation Centers',
'Leisure Centers',
'Drive-In Theater',
'Attraction Farms',
'Campgrounds',
'Boating',
'Social Clubs',
'Go Karts',
'Race Tracks',
'Gun/Rifle Ranges',
'Escape Games',
'Cultural Center',
'Dog Parks',
'Yelp Events',
'Adult Entertainment',
'Virtual Reality Centers',
'Pool & Billiards',
'Indoor Playcentre',
'Paddleboarding',
'Jet Skis',
'Scavenger Hunts',
'Rafting/Kayaking',
'Club Crawl',
'Paint-Your-Own Pottery',
'Strip Clubs',
'Ziplining',
'Laser Tag',
'Scuba Diving',
'Squash',
'Beach Volleyball',
'Snorkeling',
'Racing Experience',
'Hypnosis/Hypnotherapy',
'Skydiving',
'Basketball Courts',
'Outdoor Movies',
'Skiing',
'Wildlife Hunting Ranges',
'Experiences',
'Hang Gliding',
'Flyboarding',
'Amusement Parks',
'Hotels & Travel',
'Tours',
'Hotels',
'Landmarks & Historical Buildings',
'Arts & Entertainment',
'Music Venues',
'Churches',
'Religious Organizations',
'Venues & Event Spaces',
'Wedding Chapels',
'Transportation',
'Taxis',
'Horse Racing',
'Casinos',
'Parks',
'Country Dance Halls',
'Festivals',
'Golf',
'Hiking',
'Tennis',
'Bed & Breakfast',
'Guest Houses',
'Climbing',
'Arcades',
'Art Galleries',
'Adult',
'Archery',
'Airports',
'Hostels',
'Bus Tours',
'Sailing',
'Country Clubs',
'Farms',
'Airport Terminals',
'Airlines',
'Fishing',
'Rest Stops',
'Community Centers',
'Diving',
'Horse Boarding',
'Horseback Riding',
'Zoos',
'Botanical Gardens',
'Pumpkin Patches',
'Haunted Houses',
'Rock Climbing',
'Disc Golf',
'Wineries',
'Lakes',
'Historical Tours',
'Health Retreats',
'Aerial Tours',
'Hot Air Balloons',
'Mountain Biking',
'Oxygen Bars',
'Marinas',
'Water Parks',
'Pool Halls',
'Beer Tours',
'Food Tours',
'Baseball Fields',
'Ranches',
'Nudist',
'Buddhist Temples',
'LAN Centers',
'Art Museums',
'Public Art',
'Wine Tours',
'Axe Throwing',
'Boat Tours',
'Ski Resorts',
'Dive Shops',
'Cabaret',
'Castles',
'Rolfing',
'Cannabis Collective',
'Cannabis Tours',
'Architectural Tours',
'Pick Your Own Farms',
'Bar Crawl',
'Observatories',
'Unofficial Yelp Events',
'Rodeo',
'Art Tours',
'Bike tours',
'Children\'s Museums',
'Planetarium',
'Community Gardens',
'Sledding',
'Carousels',
'General Festivals',
]